### ISSUE TITLE
Learn Braille Beta icon

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learn-braille#66]
Special icon for the beta version of the app. Mb small letter beta in the right bottom.

**Comment by zuevval** [comment]
@winter-yuki  note that Anna is not obliged to read any of your messages and issues here because we did not consent with her to manage our workflow this way beforehand. Moreover, we have a nice Trello scrumboard. Consider adding this to TODO for next sprint. I would rather disapprove you of abusing GitHub projects.

**Comment by winter-yuki** [comment]
Done in #72
